### ISSUE TITLE
Handle exceptions

### ISSUE THREAD

**Issue by luciuz** [cranetm/yii2-json-rpc-2.0#10]
Hello!

How to handle all exceptions and send response with json-rpc-2.0 format with code 200? For example, exceptions from the Request?

**Comment by cranetm** [comment]
`try {`
`    $classInstance->method1();`
`    $classInstance->method2();`
`    .....`
`} catch (Exception $e) {`
`    throw new \JsonRpc2\Exception('General message', \JsonRpc2\Exception::INTERNAL_ERROR);`
`}`
