### ISSUE TITLE
How to throw exception?

### ISSUE THREAD

**Issue by temirfe** [cranetm/yii2-json-rpc-2.0#25]
I need to return error with specific codes according to third party docs. Whatever I do it returns `{"jsonrpc":"2.0","id":2032,"error":{"code":-32603,"message":"Internal error","data":null}}`. How can I control error response?

**Comment by cranetm** [comment]
Use Exception class from JsonRpc2, expample:
`new Exception(Yii::t('yii', 'Invalid Request'), Exception::INVALID_REQUEST)`
