### ISSUE TITLE
Arrays inside DTO is not supported

### ISSUE THREAD

**Issue by tQuant** [cranetm/yii2-json-rpc-2.0#8]
When i place "string[]" inside Dto, it parsed as "string" and not as array of strings

```
class RpcResponse extends Dto {
    ...
    /** @var string[] */
    public $errors;
}
```

**Comment by cranetm** [comment]
very strange, i am sure that array of strings works correctly. 
Ok, i will check it again.

**Comment by tQuant** [comment]
Ok, it fixed in dev-master, but why you do not update version number?
When you install it from composer, you get very old version

**Comment by cranetm** [comment]
Sorry for that. I created new 1.2.4 release.
